// ============================================================
// plugins/copy/copy-button.ts
// ============================================================

const ICON_COPY = '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>';
const ICON_CHECK = '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>';

export function getCopyButtonScript(): string {
  const lines: string[] = [
    `;(function () {`,
    `  var ICON_COPY = '${ICON_COPY}'`,
    `  var ICON_CHECK = '${ICON_CHECK}'`,
    ``,
    `  function fallbackCopy(text) {`,
    `    var ta = document.createElement('textarea')`,
    `    ta.value = text`,
    `    ta.style.cssText = 'position:fixed;left:-9999px;top:-9999px;opacity:0'`,
    `    document.body.appendChild(ta)`,
    `    ta.focus(); ta.select()`,
    `    try { document.execCommand('copy') } catch (e) {}`,
    `    document.body.removeChild(ta)`,
    `  }`,
    `  function copyText(text, onDone) {`,
    `    if (navigator.clipboard && navigator.clipboard.writeText) {`,
    `      navigator.clipboard.writeText(text).then(onDone).catch(function () { fallbackCopy(text); onDone() })`,
    `    } else {`,
    `      fallbackCopy(text); onDone()`,
    `    }`,
    `  }`,
    `  function flashBtn(btn, cells) {`,
    `    btn.innerHTML = ICON_CHECK`,
    `    btn.classList.add('copied')`,
    `    cells.forEach(function (s) { s.classList.add('code-line--flash') })`,
    `    setTimeout(function () {`,
    `      btn.innerHTML = ICON_COPY`,
    `      btn.classList.remove('copied')`,
    `      cells.forEach(function (s) { s.classList.remove('code-line--flash') })`,
    `    }, 1800)`,
    `  }`,
    ``,
    `  window.__mdsone_copy = function (container) {`,
    `    container.querySelectorAll('pre').forEach(function (pre) {`,
    `      if (pre.querySelector('.copy-btn')) return`,
    `      var btn = document.createElement('button')`,
    `      btn.className = 'copy-btn'`,
    `      btn.setAttribute('aria-label', 'Copy code')`,
    `      btn.setAttribute('type', 'button')`,
    `      btn.innerHTML = ICON_COPY`,
    `      btn.addEventListener('click', function () {`,
    `        var codeEl = pre.querySelector('code')`,
    `        var codeLines = codeEl ? codeEl.querySelectorAll('.code-line') : null`,
    `        var text = (codeLines && codeLines.length)`,
    `          ? Array.from(codeLines).map(function (s) { return s.textContent }).join('\\n')`,
    `          : (codeEl ? codeEl.textContent : pre.textContent)`,
    `        copyText(text, function () {`,
    `          btn.innerHTML = ICON_CHECK`,
    `          btn.classList.add('copied')`,
    `          setTimeout(function () { btn.innerHTML = ICON_COPY; btn.classList.remove('copied') }, 2000)`,
    `        })`,
    `      })`,
    `      pre.appendChild(btn)`,
    `    })`,
    `  }`,
    ``,
    `  window.__mdsone_line_copy = function (container) {`,
    `    container.querySelectorAll('pre[data-line-copy-ready="1"]').forEach(function (pre) {`,
    `      var codeEl = pre.querySelector('code')`,
    `      if (!codeEl || codeEl.dataset.lineCopyBound === '1') return`,
    `      codeEl.dataset.lineCopyBound = '1'`,
    `      codeEl.addEventListener('click', function (e) {`,
    `        var btn = e.target.closest('.line-copy-btn')`,
    `        if (!btn) return`,
    `        var span = btn.closest('.code-line--cmd')`,
    `        if (!span) return`,
    `        var text = decodeURIComponent(span.dataset.cmd || '')`,
    `        if (!text) return`,
    `        e.stopPropagation()`,
    `        copyText(text, function () {`,
    `          flashBtn(btn, Array.from(codeEl.querySelectorAll('[data-cmd="' + span.dataset.cmd + '"]')))`,
    `        })`,
    `      })`,
    `      codeEl.addEventListener('mouseover', function (e) {`,
    `        var span = e.target.closest('.code-line--cmd')`,
    `        if (!span) return`,
    `        codeEl.querySelectorAll('[data-cmd="' + span.dataset.cmd + '"]').forEach(function (s) { s.classList.add('code-line--hover') })`,
    `      })`,
    `      codeEl.addEventListener('mouseout', function (e) {`,
    `        var span = e.target.closest('.code-line--cmd')`,
    `        if (!span) return`,
    `        codeEl.querySelectorAll('[data-cmd="' + span.dataset.cmd + '"]').forEach(function (s) { s.classList.remove('code-line--hover') })`,
    `      })`,
    `    })`,
    `  }`,
    ``,
    `  window.__mdsone_cmd_copy = function (container) {`,
    `    container.querySelectorAll('pre[data-cmd-copy-ready="1"]').forEach(function (pre) {`,
    `      var codeEl = pre.querySelector('code')`,
    `      if (!codeEl || codeEl.dataset.cmdCopyBound === '1') return`,
    `      codeEl.dataset.cmdCopyBound = '1'`,
    `      codeEl.addEventListener('click', function (e) {`,
    `        var btn = e.target.closest('.sec-copy-btn')`,
    `        if (!btn) return`,
    `        var head = btn.closest('.code-line--sec-head')`,
    `        if (!head) return`,
    `        var text = decodeURIComponent(head.dataset.sec || '')`,
    `        if (!text) return`,
    `        e.stopPropagation()`,
    `        var sid = head.dataset.secId`,
    `        var codeCells = Array.from(codeEl.querySelectorAll('.code-line--sec-code[data-sec-id="' + sid + '"]'))`,
    `        copyText(text, function () { flashBtn(btn, codeCells) })`,
    `      })`,
    `      function getSecId(el) {`,
    `        var head = el.closest('.code-line--sec-head')`,
    `        if (head) return head.dataset.secId`,
    `        var code = el.closest('.code-line--sec-code')`,
    `        if (code) return code.dataset.secId`,
    `        return null`,
    `      }`,
    `      codeEl.addEventListener('mouseover', function (e) {`,
    `        var sid = getSecId(e.target)`,
    `        if (sid === null) return`,
    `        var head = codeEl.querySelector('.code-line--sec-head[data-sec-id="' + sid + '"]')`,
    `        if (head) head.classList.add('sec-active')`,
    `        codeEl.querySelectorAll('.code-line--sec-code[data-sec-id="' + sid + '"]').forEach(function (s) { s.classList.add('code-line--hover') })`,
    `      })`,
    `      codeEl.addEventListener('mouseout', function (e) {`,
    `        var sid = getSecId(e.target)`,
    `        if (sid === null) return`,
    `        var head = codeEl.querySelector('.code-line--sec-head[data-sec-id="' + sid + '"]')`,
    `        if (head) head.classList.remove('sec-active')`,
    `        codeEl.querySelectorAll('.code-line--sec-code[data-sec-id="' + sid + '"]').forEach(function (s) { s.classList.remove('code-line--hover') })`,
    `      })`,
    `    })`,
    `  }`,
    `})()`,
  ];
  return lines.join("\n");
}

export function getLineCopyStyle(): string {
  return [
    `.code-line { display: block; position: relative; line-height: inherit; margin: 0; padding: 0; }`,
    `.code-line--cmd {`,
    `  border-radius: 3px;`,
    `  padding-right: 2rem;`,
    `  transition: background 0.12s;`,
    `}`,
    `.code-line--hover { background: rgba(128,128,128,0.12); }`,
    `.code-line--flash { background: rgba(55,138,221,0.18) !important; }`,
    `.line-copy-btn {`,
    `  position: absolute;`,
    `  right: 4px;`,
    `  top: 50%;`,
    `  transform: translateY(-50%);`,
    `  display: inline-flex;`,
    `  align-items: center;`,
    `  justify-content: center;`,
    `  width: 22px; height: 22px;`,
    `  padding: 0; border: none; border-radius: 4px;`,
    `  background: transparent; color: inherit;`,
    `  opacity: 0; cursor: pointer;`,
    `  transition: opacity 0.15s, background 0.12s;`,
    `}`,
    `.code-line--cmd:hover .line-copy-btn,`,
    `.line-copy-btn.copied { opacity: 0.75; }`,
    `.line-copy-btn:hover { opacity: 1 !important; background: rgba(128,128,128,0.18); }`,
  ].join("\n");
}

export function getCmdCopyStyle(): string {
  return [
    `.code-line { display: block; position: relative; line-height: inherit; margin: 0; padding: 0; }`,
    `.code-line--sec-head {`,
    `  display: flex;`,
    `  align-items: center;`,
    `  line-height: inherit;`,
    `  gap: 6px;`,
    `  border-radius: 3px;`,
    `  transition: background 0.12s;`,
    `}`,
    `.sec-comment {`,
    `  flex: 1 1 0;`,
    `  min-width: 0;`,
    `  overflow: hidden;`,
    `  text-overflow: ellipsis;`,
    `  white-space: nowrap;`,
    `  line-height: inherit;`,
    `}`,
    `.code-line--flash { background: rgba(55,138,221,0.18) !important; }`,
    `.sec-copy-btn {`,
    `  flex: 0 0 auto;`,
    `  display: inline-flex;`,
    `  align-items: center;`,
    `  justify-content: center;`,
    `  width: 1.4em; height: 1.4em;`,
    `  padding: 0; border: none; border-radius: 4px;`,
    `  background: transparent; color: inherit;`,
    `  opacity: 0; cursor: pointer;`,
    `  transition: opacity 0.15s, background 0.12s;`,
    `}`,
    `.code-line--sec-head:hover .sec-copy-btn,`,
    `.code-line--sec-head.sec-active .sec-copy-btn,`,
    `.sec-copy-btn.copied { opacity: 0.75; }`,
    `.sec-copy-btn:hover { opacity: 1 !important; background: rgba(128,128,128,0.18); }`,
  ].join("\n");
}
