#!/usr/bin/env node
// ============================================================
// Bun/build.mjs
// Build mdsone executable with Bun and embed runtime assets.
// ============================================================

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const __filename = fileURLToPath(import.meta.url);
const bunDir = path.dirname(__filename);
const projectRoot = path.resolve(bunDir, "..");
const generatedDir = path.join(bunDir, "generated");
const generatedAssetsFile = path.join(generatedDir, "embedded-assets.ts");
const distDir = path.join(bunDir, "dist");
const entryFile = path.join(bunDir, "entry.ts");
const EMBED_ROOT_TEMPLATES = "templates";
const EMBED_ROOT_LOCALES = "locales";
const EMBED_ROOT_KATEX = "node_modules/katex/dist";
const TMP_DIR = path.join(bunDir, "_tmp_compile");
const BUN_RUNTIME_TMP_DIR = path.join(bunDir, "_tmp_bun_runtime");
const WINDOWS_ICON_SOURCE = path.join(projectRoot, "logo", "mdsone.ico");
const GENERATED_WINDOWS_ICON = path.join(generatedDir, "mdsone_icon.ico");
const PLUGIN_ASSET_GENERATOR = path.join(projectRoot, "scripts", "generate-plugin-assets.mjs");

const BUILD_TARGETS = [
  {
    target: "bun-windows-x64",
    outputName: "mdsone-win-x64.exe",
    binaryName: "mdsone.exe",
  },
  {
    target: "bun-linux-x64",
    outputName: "mdsone-linux-x64",
    binaryName: "mdsone",
  },
  {
    target: "bun-darwin-x64",
    outputName: "mdsone-macos-x64",
    binaryName: "mdsone",
  },
  {
    target: "bun-darwin-arm64",
    outputName: "mdsone-macos-arm64",
    binaryName: "mdsone",
  },
];

function resolveBuildTargets() {
  const raw = process.env.BUN_BUILD_TARGETS?.trim();
  if (!raw) return BUILD_TARGETS;

  const wanted = new Set(
    raw
      .split(",")
      .map((x) => x.trim())
      .filter(Boolean)
  );
  if (wanted.size === 0) return BUILD_TARGETS;

  const filtered = BUILD_TARGETS.filter(
    (item) => wanted.has(item.target) || wanted.has(item.outputName)
  );
  if (filtered.length === 0) {
    throw new Error(
      `[bun-build] BUN_BUILD_TARGETS does not match any known target: ${raw}`
    );
  }

  return filtered;
}

function sleepMs(ms) {
  const sab = new SharedArrayBuffer(4);
  const view = new Int32Array(sab);
  Atomics.wait(view, 0, 0, ms);
}

function toPosix(p) {
  return p.split(path.sep).join("/");
}

function listFilesRecursive(absDir) {
  const out = [];
  const entries = fs.readdirSync(absDir, { withFileTypes: true });
  for (const entry of entries) {
    const abs = path.join(absDir, entry.name);
    if (entry.isDirectory()) {
      out.push(...listFilesRecursive(abs));
      continue;
    }
    if (!entry.isFile()) continue;
    out.push(abs);
  }
  return out;
}

function collectEmbeddedLogicalPaths() {
  const requiredRoots = [EMBED_ROOT_TEMPLATES, EMBED_ROOT_LOCALES];
  const logicalPaths = [];

  for (const root of requiredRoots) {
    const absRoot = path.join(projectRoot, root);
    if (!fs.existsSync(absRoot)) {
      throw new Error(`Missing required embed directory: ${absRoot}`);
    }
    const files = listFilesRecursive(absRoot);
    for (const file of files) {
      logicalPaths.push(toPosix(path.relative(projectRoot, file)));
    }
  }

  const katexDistRoot = path.join(projectRoot, EMBED_ROOT_KATEX);
  if (fs.existsSync(katexDistRoot)) {
    const katexCss = path.join(katexDistRoot, "katex.min.css");
    if (fs.existsSync(katexCss)) {
      logicalPaths.push(toPosix(path.relative(projectRoot, katexCss)));
    }
    const fontsDir = path.join(katexDistRoot, "fonts");
    if (fs.existsSync(fontsDir)) {
      const fontFiles = listFilesRecursive(fontsDir);
      for (const file of fontFiles) {
        logicalPaths.push(toPosix(path.relative(projectRoot, file)));
      }
    }
  }

  return [...new Set(logicalPaths)].sort();
}

function writeGeneratedAssetsModule(logicalPaths) {
  fs.mkdirSync(generatedDir, { recursive: true });

  const lines = [];
  lines.push("// AUTO-GENERATED FILE. DO NOT EDIT.");
  lines.push("// Generated by Bun/build.mjs");
  lines.push("");
  lines.push("export type EmbeddedAsset = { logicalPath: string; embeddedPath: string };");
  lines.push("");

  for (const [index, logicalPath] of logicalPaths.entries()) {
    lines.push(`import asset_${index} from "../../${logicalPath}" with { type: "file" };`);
  }

  lines.push("");
  lines.push("export const EMBEDDED_ROOTS = {");
  lines.push(`  templates: "${EMBED_ROOT_TEMPLATES}",`);
  lines.push(`  locales: "${EMBED_ROOT_LOCALES}",`);
  lines.push(`  katexDist: "${EMBED_ROOT_KATEX}",`);
  lines.push("} as const;");
  lines.push("");
  lines.push("export const EMBEDDED_ASSETS: EmbeddedAsset[] = [");
  for (const [index, logicalPath] of logicalPaths.entries()) {
    lines.push(`  { logicalPath: "${logicalPath}", embeddedPath: asset_${index} },`);
  }
  lines.push("];");
  lines.push("");

  fs.writeFileSync(generatedAssetsFile, lines.join("\n"), "utf8");
}

function removeFileWithRetry(filePath, maxRetry = 6) {
  if (!fs.existsSync(filePath)) return;
  for (let i = 0; i < maxRetry; i++) {
    try {
      fs.rmSync(filePath, { force: true });
      return;
    } catch (error) {
      const code = error && typeof error === "object" ? error.code : "";
      const isBusy = code === "EBUSY" || code === "EPERM";
      if (!isBusy || i === maxRetry - 1) {
        throw error;
      }
      sleepMs(180 * (i + 1));
    }
  }
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function removeDirWithRetry(dirPath, maxRetry = 6) {
  if (!fs.existsSync(dirPath)) return;
  for (let i = 0; i < maxRetry; i++) {
    try {
      fs.rmSync(dirPath, { recursive: true, force: true });
      return;
    } catch (error) {
      const code = error && typeof error === "object" ? error.code : "";
      const isBusy = code === "EBUSY" || code === "EPERM";
      if (!isBusy || i === maxRetry - 1) {
        throw error;
      }
      sleepMs(180 * (i + 1));
    }
  }
}

function escapePsSingle(value) {
  return String(value).replace(/'/g, "''");
}

function resolveWindowsIconPath() {
  if (!fs.existsSync(WINDOWS_ICON_SOURCE)) {
    console.warn(`[bun-build] windows icon source not found: ${WINDOWS_ICON_SOURCE}`);
    return null;
  }

  const ext = path.extname(WINDOWS_ICON_SOURCE).toLowerCase();
  if (ext === ".ico") return WINDOWS_ICON_SOURCE;
  if (ext !== ".png") {
    console.warn(`[bun-build] unsupported icon extension: ${ext} (expected .png or .ico)`);
    return null;
  }

  ensureDir(generatedDir);
  const pngPath = escapePsSingle(WINDOWS_ICON_SOURCE);
  const icoPath = escapePsSingle(GENERATED_WINDOWS_ICON);
  const script = [
    "Add-Type -AssemblyName System.Drawing",
    `$png='${pngPath}'`,
    `$ico='${icoPath}'`,
    "$bmp=[System.Drawing.Bitmap]::FromFile($png)",
    "$icon=[System.Drawing.Icon]::FromHandle($bmp.GetHicon())",
    "$fs=[System.IO.File]::Open($ico,[System.IO.FileMode]::Create)",
    "$icon.Save($fs)",
    "$fs.Close()",
    "$icon.Dispose()",
    "$bmp.Dispose()",
  ].join("; ");

  const result = spawnSync("powershell", ["-NoProfile", "-Command", script], {
    cwd: projectRoot,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0 || !fs.existsSync(GENERATED_WINDOWS_ICON)) {
    console.warn("[bun-build] failed to generate .ico from PNG; windows build will use default icon");
    return null;
  }

  return GENERATED_WINDOWS_ICON;
}

function compileTarget(target, outFile, windowsIconPath) {
  removeFileWithRetry(outFile);
  const args = ["build", entryFile, "--compile", "--outfile", outFile, `--target=${target}`];
  if (target.includes("windows") && windowsIconPath && process.platform === "win32") {
    args.push(`--windows-icon=${windowsIconPath}`);
  } else if (target.includes("windows") && windowsIconPath && process.platform !== "win32") {
    console.warn("[bun-build] skip --windows-icon: only supported when compiling on Windows host");
  }
  if (process.env.BUN_COMPILE_MINIFY === "1") args.push("--minify");

  const env = {
    ...process.env,
    TMP: BUN_RUNTIME_TMP_DIR,
    TEMP: BUN_RUNTIME_TMP_DIR,
    TMPDIR: BUN_RUNTIME_TMP_DIR,
  };

  const maxAttempts = Math.max(1, Number(process.env.BUN_COMPILE_RETRY ?? "3") || 3);
  let lastStatus = 1;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const result = spawnSync("bun", args, {
      cwd: projectRoot,
      stdio: "inherit",
      shell: process.platform === "win32",
      env,
    });
    const status = result.status ?? 1;
    if (status === 0) {
      lastStatus = 0;
      break;
    }
    lastStatus = status;
    if (attempt < maxAttempts) {
      console.warn(`[bun-build] compile failed (${target}), retry ${attempt}/${maxAttempts - 1}...`);
      sleepMs(250 * attempt);
    }
  }

  if (lastStatus !== 0) {
    process.exit(lastStatus);
  }
  try {
    fs.chmodSync(outFile, 0o755);
  } catch {
    // Ignore chmod errors on unsupported hosts.
  }
}

function runPluginAssetGenerator() {
  if (!fs.existsSync(PLUGIN_ASSET_GENERATOR)) return;
  const result = spawnSync("node", [PLUGIN_ASSET_GENERATOR], {
    cwd: projectRoot,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function run() {
  const selectedTargets = resolveBuildTargets();
  runPluginAssetGenerator();
  const logicalPaths = collectEmbeddedLogicalPaths();
  writeGeneratedAssetsModule(logicalPaths);
  const windowsIconPath = resolveWindowsIconPath();

  ensureDir(distDir);
  ensureDir(TMP_DIR);
  ensureDir(BUN_RUNTIME_TMP_DIR);

  console.log(`[bun-build] projectRoot: ${projectRoot}`);
  console.log(`[bun-build] embedded assets: ${logicalPaths.length}`);
  console.log(`[bun-build] targets: ${selectedTargets.map((x) => x.target).join(", ")}`);
  console.log("[bun-build] executable name by platform: win=mdsone.exe, linux=mdsone, macos=mdsone");
  if (windowsIconPath) {
    console.log(`[bun-build] windows icon: ${windowsIconPath}`);
  }

  for (const item of selectedTargets) {
    const rawOutFile = path.join(TMP_DIR, item.binaryName);
    console.log(`[bun-build] compiling: ${item.target}`);
    compileTarget(item.target, rawOutFile, windowsIconPath);

    const finalOut = path.join(distDir, item.outputName);
    removeFileWithRetry(finalOut);
    fs.renameSync(rawOutFile, finalOut);
    console.log(`[bun-build] output: ${finalOut}`);
  }

  removeDirWithRetry(TMP_DIR);
  removeDirWithRetry(BUN_RUNTIME_TMP_DIR);

  console.log(`[bun-build] generated: ${generatedAssetsFile}`);
  console.log("[bun-build] done");
}

run();
