// ============================================================
// plugins/line-number/line-number.ts
// ============================================================

export function getLineNumberScript(): string {
  const lines: string[] = [
    `;(function () {`,
    `  function addNumbers(codeEl) {`,
    `    var lines = codeEl.querySelectorAll('.code-line')`,
    `    if (!lines || !lines.length) return`,
    `    lines.forEach(function (lineEl, idx) {`,
      `      if (lineEl.querySelector('.code-line-number')) return`,
      `      var num = document.createElement('span')`,
      `      num.className = 'code-line-number'`,
      `      num.textContent = String(idx + 1)`,
      `      var content = document.createElement('span')`,
      `      content.className = 'code-line-content'`,
      `      while (lineEl.firstChild) { content.appendChild(lineEl.firstChild) }`,
      `      lineEl.appendChild(num)`,
      `      lineEl.appendChild(content)`,
    `    })`,
    `  }`,
    `  function wrapLines(codeEl) {`,
    `    if (!codeEl) return`,
    `    if (codeEl.querySelector('.code-line')) {`,
    `      addNumbers(codeEl)`,
    `      return`,
    `    }`,
    `    var htmlLines = codeEl.innerHTML.split('\\n')`,
    `    if (htmlLines[htmlLines.length - 1] === '') htmlLines.pop()`,
    `    codeEl.innerHTML = htmlLines.map(function (lineHTML, idx) {`,
    `      return '<span class="code-line"><span class="code-line-number">' + (idx + 1) + '</span><span class="code-line-content">' + (lineHTML || '\\u200b') + '</span></span>'`,
    `    }).join('')`,
    `  }`,
    `  window.__mdsone_line_number = function (container) {`,
    `    container.querySelectorAll('pre').forEach(function (pre) {`,
    `      if (pre.dataset.lineNumberReady) return`,
    `      pre.dataset.lineNumberReady = '1'`,
    `      pre.classList.add('mdsone-line-number')`,
    `      var codeEl = pre.querySelector('code')`,
    `      if (!codeEl) return`,
    `      wrapLines(codeEl)`,
    `    })`,
    `  }`,
    `})()`,
  ];
  return lines.join("\n");
}

export function getLineNumberStyle(): string {
  return [
    `.mdsone-line-number {`,
    `  --mdsone-ln-gutter: 1.7em;`,
    `  --mdsone-ln-gap: 0.45em;`,
    `}`,
    `.mdsone-line-number .code-line {`,
      `  display: grid;`,
      `  grid-template-columns: var(--mdsone-ln-gutter) 1fr;`,
      `  column-gap: var(--mdsone-ln-gap);`,
      `  align-items: start;`,
    `}`,
    `.mdsone-line-number .code-line-number {`,
      `  flex: 0 0 auto;`,
      `  width: var(--mdsone-ln-gutter);`,
      `  text-align: right;`,
      `  opacity: 0.6;`,
      `  font-variant-numeric: tabular-nums;`,
      `  user-select: none;`,
      `  pointer-events: none;`,
      `  padding-right: var(--mdsone-ln-gap);`,
      `  border-right: 1px solid rgba(0,0,0,0.18);`,
    `}`,
    `.mdsone-line-number .code-line-content {`,
    `  min-width: 0;`,
    `}`,
    `.mdsone-line-number .code-line--sec-head .code-line-content {`,
    `  display: flex;`,
    `  align-items: center;`,
    `  gap: 6px;`,
    `}`,
    `html[data-theme="dark"] .mdsone-line-number .code-line-number {`,
    `  border-right-color: rgba(255,255,255,0.35);`,
    `}`,
  ].join("\n");
}
